### ISSUE TITLE
It's not working with Tablet and also Width is fixed

### ISSUE THREAD

**Issue by divyesh008** [matt-goldman/MauiMaterialEntry#1]
In MaterialEntry.xaml you have set the Width of BorderlessEntry to 200 which does not work on tablet. I have tried to remove the fixed width and set Horizontal Options="Fill" but then also it's width not increase properly. 

```
 <controls:BorderlessEntry VerticalOptions="Center"
                                      HorizontalOptions="Fill"
                                      Focused="MEEntry_Focused"
                                      Unfocused="MEEntry_Unfocused"
                                      x:Name="MEEntry"
                                      Text="{Binding Text}"
                                      HeightRequest="{OnPlatform iOS=40, MacCatalyst=40}">
```

Can we make it dynamic based on device resolution?

**Comment by matt-goldman** [comment]
Yep absolutely. I mentioned in the video that if I were doing this for real I wouldn't hard-code those values. You can use the `OnSizeAllocated` method to get the screen width and set the value based on that.
