### ISSUE TITLE
Bind to viewmodel

### ISSUE THREAD

**Issue by aminparsa18** [matt-goldman/MauiMaterialEntry#2]
So what if I wnt to bind material entry text to a string in my ViewModel of MainPage? Im trying with different binding modes and the value is not updating :(

**Comment by matt-goldman** [comment]
Have you got a code sample you can link to?

**Comment by aminparsa18** [comment]
[MauiMaterialEntry.zip](https://github.com/matt-goldman/MauiMaterialEntry/files/10393204/MauiMaterialEntry.zip)

It's based on your own source using standard mvvm toolkit maintained by Microsoft (https://github.com/CommunityToolkit/MVVM-Samples)

**Comment by aminparsa18** [comment]
Any update on this?

**Comment by matt-goldman** [comment]
Hi @aminparsa18, apologies for the late reply. I downloaded your code sample and was able to recreate the issue but I haven't had a chance to look at resolving it yet. I'll update you as soon as I can.

**Comment by MarkLFT** [comment]
Did you ever find a solution for this?  I also have not managed to find a way to bind the control text parameter.

**Comment by aminparsa18** [comment]
> Did you ever find a solution for this? I also have not managed to find a way to bind the control text parameter.

I didn't :(

**Comment by matt-goldman** [comment]
Sorry, I've been busy getting the book wrapped up. But I will take another look at it this week.

**Comment by aminparsa18** [comment]
Its really insane but I just tried one more time after a while. I removed 
**BindingContext = this;**
from constructor and now its working !!
