### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by hansmbakker** [matt-goldman/MauiMaterialEntry#3]
Hi, thank you for publishing your interesting video and book!

I'd like to ask your considerations regarding the class structure of the `MauiMaterialEntry` - instead of directly inheriting from `Entry` it inherits from `ContentView` and it contains another `BorderlessEntry` control which inherits from `Entry`.

Because of this inheritance from `ContentView` instead of `Entry`, all properties you want to pass to the actual entry need to be redefined as "passthrough" properties (currently that is only the `Text` property but what if you want to expose the `MaxLength` or the `IsPassword` properties).

I managed creating an `EntryWithBorder` control inheriting from `Entry` following https://github.com/gzadro/.NET-MAUI-custom-Entry-control and I liked the simplicity. I applied styling for the different states of `Entry` in XAML using VisualStateManager.

I see that adding an animated label on top of it, inside the control / handler code, might be more difficult though - is that something you could share some thoughts about?

**Comment by matt-goldman** [comment]
It's a trade-off. Creating all the animation and customisations inside your handlers is possible but is a lot more work, a lot less shared code, and doesn't leverage many of the advantages of using .NET MAUI. On the other hand using a `ContentView` like you said requires passing through properties.

I think the approach depends on your use case. If I were working on a n app that needed some customisation, I would take the lowest friction approach which would almost certainly be a `ContentView` (but again depends on the goal - if you're just making small modifications to `Entry` you wouldn't need it; if you're adding animations like in this example you would). If on the other hand I was working on a control library, I might consider the handler approach as you can't anticipate all the properties people may need to access.

**Comment by hansmbakker** [comment]
Thank you! This helped me to understand the use cases for each option better.
